
[workspace]
default-members = ["crates/bin"]
resolver = "2"
members = [
  "crates/assets",
  "crates/bin",
  "crates/settings",
  "crates/context",
  "crates/ui",
  "crates/action",
]

[workspace.package]
publish = false
edition = "2024"

[workspace.dependencies]
assets = { path = "crates/assets" }
action = { path = "crates/action" }
context = { path = "crates/context" }
settings = { path = "crates/settings" }
anyhow = "1.0.102"
gpui = "0.2.2"
gpui-component = "0.5.1"
rust-embed = { version = "8.11.0", features = ["debug-embed"] }
serde = { version = "1.0.229", features = ["serde_derive"] }
uuid = { version = "1.25.0", features = ["v4"] }
http = "1.5.0"
serde_with = "3.22.0"
toml = "1.1.4"
thiserror = "2.0.20"
ui = { path = "crates/ui" }
# NOTE: target_os no need to install at root
# raw-window-handle = "0.6"
# objc2 = "0.6"
# objc2-app-kit = { version = "0.3" }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
